#nome = input('Olá digite seu nome:')
#print('Olá seja bem vindo!',nome,'Um prazer em conhecer.')
dia = input('Digite o dia:')
mes = input('Digite o mes:')
ano = input('Digite o ano:')
print('Voce nasceu no dia',dia,'de',mes,'de',ano,'correto')